### ISSUE TITLE
Connection to be made between APIGateway and DataRetrieval microservices.

### ISSUE THREAD

**Issue by CleverParty** [airavata-courses/SquirtleSquad#14]
Async Connection through kakfa is to be established.

**Comment by CleverParty** [comment]
Aysnc Connection has been made, and passes data to the ModelExecution microservice.

**Comment by CleverParty** [comment]
https://github.com/airavata-courses/SquirtleSquad/commit/090167751a6e068abe1fcd0a18a3a7e6d723c103 
please implement this commit

**Comment by anuragkumar95** [comment]
I believe this issue has been resolved
