### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/SquirtleSquad#17]
In the Microservices based on NodeJS and react please mention npm install before the npm run dev command. As a third person not well acquainted with nodejs would not be able to troubleshoot this problem efficiently
ie. Add this instead: 
$ cd SquirtleSquad/APIGateway
$ npm install
$ npm run dev

for all microservices

**Comment by ishita-kumar** [comment]
**Installing golang**
sudo apt-get go-golang does not work for ubuntu? 
Am i doing something wrong?
I found this : 
https://stackoverflow.com/questions/32633131/go-setup-on-ubuntu

**Comment by CleverParty** [comment]
> **Installing golang**
> sudo apt-get go-golang does not work for ubuntu?
> Am i doing something wrong?
> I found this :
> https://stackoverflow.com/questions/32633131/go-setup-on-ubuntu

It was a small documentation error, the docs have now been updated to reflect the golang installation

**Comment by anuragkumar95** [comment]
this has been added in the readme...
