### ISSUE TITLE
Not Able to jump to Login Page after Registering New User

### ISSUE THREAD

**Issue by Arjunbhavsar** [airavata-courses/SquirtleSquad#18]
Once I register a new User. It should redirect to the Login page so that we can proceed with login Activity.

**Comment by CleverParty** [comment]
this feature bug has been addressed now,
the routing now works as expected

**Comment by CleverParty** [comment]
this feature bug has been addressed now,
the routing now works as expected
thanks for testing

**Comment by Arjunbhavsar** [comment]
I have tested it again and it Looks good Now.
