### ISSUE TITLE
Session Activity isn't restored after login

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/SquirtleSquad#19]

**Comment by CleverParty** [comment]
Okay, the connection between UserManagement and SessionManagment has been modified now
@maxprime1 checkout this connection and verify the system

**Comment by maxprime1** [comment]
Fixed it in 3e15b6a158a4b6595f4a7fedc2691b15e8ccbd53

**Comment by ishita-kumar** [comment]
Verified
