### ISSUE TITLE
Dashboard -  download Button not working 

### ISSUE THREAD

**Issue by Arjunbhavsar** [airavata-courses/SquirtleSquad#21]
I am Getting Following Error in Terminal -

goroutine 35 [running]:
main.main.func3(0x8f7360, 0xc4200b2c80, 0xc4201c4008, 0x89acc4, 0xd, 0x8f5da0, 0xc42011a960, 0x8b2508, 0x56, 0xc4201d6600, ...)

**Comment by CleverParty** [comment]
This seems to be an internal package error thrown by the go microservice which should be running.
Please try to use -- > go get "github.com/Shopify/sarama" or try to use " go get -u all " on your system.

**Comment by Arjunbhavsar** [comment]
Yes, thanks for help.

It's working as expected Now.
