### ISSUE TITLE
Error: While trying to run ModelExecution.py

### ISSUE THREAD

**Issue by shivamriky** [airavata-courses/SquirtleSquad#27]
![Ass_4](https://user-images.githubusercontent.com/5948157/74495216-243ea880-4efd-11ea-990b-5a4e10993a5e.png)

I think the readme needs to be updated for installing support libraries

**Comment by anuragkumar95** [comment]
I think this package comes with anaconda3. In the readme, I have specifically instructed to install anaconda. You would not have this issue if you have anaconda installed. The major reason for pushing for anaconda is that the pyART package used in this project is available through conda only.

**Comment by shivamriky** [comment]
Looks good. Thanks for the explanation.
