### ISSUE TITLE
Replace Travis with Jenkins

### ISSUE THREAD

**Issue by anuragkumar95** [airavata-courses/SquirtleSquad#41]
We need to use Jenkins to primarily fix CD

**Comment by CleverParty** [comment]
jenkins server is running on http://149.165.171.111:8080/ 
username : admin
password : admin123
build is triggered on every push to master branch

**Comment by CleverParty** [comment]
temporary the github SCM trigger has been deactivated to prevent mesage.yml file to have duplicate system variables.

**Comment by CleverParty** [comment]
github trigger is back, just push to master to trigger

**Comment by anuragkumar95** [comment]
Jenkins still doesn't work with istio. Working version of Jenkins is at commit 2ec64d956f8648835a1e6efe105a66659ff1c31b
