### ISSUE TITLE
Integrating istio onto the current implementation of WeatherApp

### ISSUE THREAD

**Issue by CleverParty** [airavata-courses/SquirtleSquad#43]
Milestones: 
-Able to view the deployments.
-Able to display kiali dashboard with live updates on the website hosted at http://149.165.171.111:30000/
-Able to test individual microservice failure and the effect each microservice has on the entire architecture.

**Comment by anuragkumar95** [comment]
Istio is integrated with our application. However, we still need to fix the CD with Jenkins

**Comment by CleverParty** [comment]
istio has been integrated with the microservices.
