### ISSUE TITLE
Integrating istio sidecar proxies

### ISSUE THREAD

**Issue by CleverParty** [airavata-courses/SquirtleSquad#44]
-After sidecar injection , we are facing with rejected requests with the istio-proxies that are configured on each sidecar.
<img width="1440" alt="Screen Shot 2020-04-30 at 6 23 10 PM" src="https://user-images.githubusercontent.com/22660225/80764958-d1de5280-8b0f-11ea-8082-0fa7f3b4d7b6.png">

**Comment by CleverParty** [comment]
We have noted:
-Investigated the issues caused by each istio injected sidecar proxy .
We have identified that there is a configuration setup variable that needs to includes mongo as a service. (https://preliminary.istio.io/docs/reference/config/networking/service-entry/)
- We also have located that each microservice must be injected seperately with their own mongo config changes.

- this ServiceEntry setup must be changed.

**Comment by maxprime1** [comment]
Unable to maintain multiple secret keys for multiple mongo db databases

**Comment by maxprime1** [comment]
Fixed the error for sessionmanagement in istios
0a2190aa141c998cd8165c7296a5d2c1e21741df

**Comment by maxprime1** [comment]
Fixed the error for usermanagement in istios
13b7f2885de9b7269a454d7f75d887713ebe7e96

**Comment by CleverParty** [comment]
[](https://github.com/airavata-courses/SquirtleSquad/commit/fb85605d72b2c2c30f88c7a7da84015b3f1af8d5)
